### PR TITLE
[ci-skip] Add HuskHomes and HuskTowns integrations

### PR DESCRIPTION
**Pull request by WiIIiam278**
Adds HuskHomes and HuskTowns to ADDONS-INTEGRATIONS.md

### CODE REVIEW

**Comment by BillyGalbreath** [comment]
I'm not seeing any mention of Pl3xMap on their resource page or wiki

https://github.com/WiIIiam278/HuskHomes2/wiki/Map-Integration

**Comment by WiIIiam278** [comment]
Sorry, I hadn't taken the time to update the documentation there yet. I've now done so.

**Comment by granny** [comment]
Not seeing any mention of pl3xmap on all three of husktown's resource pages (spigotmc, polymart, songoda)

Would like to note that you missed something here ;) [William278/HuskHomes2/…/PlexMap.java#L151](https://github.com/WiIIiam278/HuskHomes2/blob/32bd4792eecd8551e91aa8bc22ea63294a9e14e2/src/main/java/me/william278/huskhomes2/integrations/map/Pl3xMap.java#L151)

**Comment by WiIIiam278** [comment]
> Not seeing any mention of pl3xmap on all three of husktown's resource pages (spigotmc, polymart, songoda)
Oh, fair enough. I missed the resource description pages. I've gone in and corrected those. I appreciate the standard of requiring high quality documentation before adding here 👍. I haven't updated all the .png graphics, but have added the relevant links to the descriptions I hope that's OK.

> Would like to note that you missed something here ;) [William278/HuskHomes2/…/PlexMap.java#L151](https://github.com/WiIIiam278/HuskHomes2/blob/32bd4792eecd8551e91aa8bc22ea63294a9e14e2/src/main/java/me/william278/huskhomes2/integrations/map/Pl3xMap.java#L151)
Thanks, I'm glad someone is paying attention there! 😄

**Pull request merged**
